module.exports = [
    {
        "url":"https://www.google.com/",
        "priority":"9"
    },
    {
        "url":"https://www.facebook.com/",
        "priority":"2"
    },
    {
        "url":"https://www.github.com/",
        "priority":"3"
    },
    {
        "url":"https://www.amazon.com/",
        "priority":"4"
    },
    {
        "url":"https://www.flipkart.com/",
        "priority":"5"
    },
    {
        "url":"https://www.kratikal.com/",
        "priority":"6"
    },
    {
        "url":"https://www.hackerrank.com/",
        "priority":"7"
    },
    {
        "url":"https://www.youtube.com/",
        "priority":"8"
    },
    {
        "url":"https://www.doesnotex333ist.com/",
        "priority":"0"
    }


]